import React from 'react'

export const metadata = {
  title: 'Contact',
  description: 'Generated by create next app',
}
const CotactUs = () => {
  return (
    <div>
      contact us page is this
    </div>
  )
}

export default CotactUs
