import Footer from "@/global/Footer"
import Header from "@/global/Header"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{padding:0,margin:0}} >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
